###

GET http://localhost:4000/coins/64fe34f8ab51f404081a1b6a

###

POST http://localhost:4000/coin/new
Content-Type: application/json

{
    "ticker": "LTC",
    "amount": 0.32,
    "name": "Cardani",
    "user_id": "64fe34f8ab51f404081a1b62"
}

###

POST http://localhost:4000/coin/new
Content-Type: application/json

{
    "name": "Etherium",
    "ticker": "ETH",
    "amount": 0.12,
    "user_id": "64fe34f8ab51f404081a1b6a"
}

###

PUT http://localhost:4000/coin/update/64fe382a8418c413de514ed0 
Content-Type: application/json

{
  "amount": 0.63
}

###

DELETE http://localhost:4000/coin/delete/64f8e0e2dedf444d3f0ca75a

###

POST http://localhost:4000/signup
Content-Type: application/json

{
  "email": "joe+8@gmail.com",
  "password": "12345"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "email": "joe+1@gmail.com",
  "password": "12345"
}

###

GET http://localhost:4000/users
